sudo: required
language: ruby

rvm:
  - 2.5.5

services:
  - docker

cache:
  - bundler

before_install:
  - gem install bundler

install:
  - bundle install

script:
  - gem build sensu-plugins-ruby.gemspec
  - gem install sensu-plugins-ruby-*.gem

before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"

deploy:
  - provider: rubygems
    api_key:
      secure: Vha7m1Li7Jg7Md81siv18OvnqBaZHGnhhCIfe1ASxf5fe22EbLzqevBgSg8NI2MbOXOjOXZpO1WnWaeQKVRToYdqfLPRVQ0IwhvJxlT+fiYigczhj9jxNejIE7vfuJ/wWkjPubmRBvQBlr1eVT5donoyeCGlEoUGYoHF2AJ5rm2Yy056DxEFLXkYskpJZh49JIaTkELkSk8IfGKmDql2YDJQdqkwLcsz4Zg2cS8I4WlwpsW8bQjvTeuCKKIjnh3ylt9BYLCrs7kUPhXOyTdJzy8JxTzA/J2aM0jN0/PRfXMhzOtQfjywdJlCuVA3WTLBCr6Ny+ciS7W9kE5cHAm9SaPCZKPWPlhZB0KF1y7RpEEY2r+io3AE4oqPNBRHIXjfahyDbd71SqlFC05ZdUThVjGo9rgOHJUyxDjQ44KwjRKiX1e6MVouGHTjDjgATF2dqd1QOGiSKuqw7NmIMxge8unwz+FGVmMxCNqcVAfbMsZ1F0Unyh3KnWo7lp/cr7CyyWTRaRjC4le7l5120e1Akcx0rsHE8vlcqBbHGANtM4qW+qihUtVO0CKN+sPSsIRbmcC9gshIxrsxWX9agnT49UYB5kCy3ajkELjRHCDFtEXKm8DYzxcBRPD68mEZgJxEU63ZSfF1BZfM0Km63tyoxEtwr4CusAG1zIMsJZzWhmQ=
    gem: sensu-plugins-ruby
    on:
      tags: true
      all_branches: true
      rvm: 2.5.5
      repo: SICSoftwareGmbH/sensu-plugins-ruby

  - provider: script
    script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-ruby
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      rvm: 2.5.5

env:
  global:
    secure: "wCy0rkujPL05QmhgC4m2896hsUmVn2aoolF9nF3IYklHTYLRUAcTpWPbjKNse0KkVJGNu1TGpxoKqD5IYyWagYfarI/mHPlkV7/JIVMOGx01AWT+gPIfF2AbRdzaYwhQGmPb1I4lAg4ZGXTQdIitSPQaKXT4Bqi5XdlOwbAY1vqtUI8nylEmepSKi32a1kz0ArDkrEX1FUeK0B4m3lxFGf9K+ZybYxx2TOhvVtuBLQSZHfsgcczO7LgUClJVpiJoXaAHUOG5Iur4G5bDEGcMSWA+w32NqEmSg20k3ZsSYhMTre9G937YCGpjnWybLy44tqPLs6FW1SB2HooyvI5yDRWGjPhHLjRlbsU7GgIGrKUbAIbAcXMgQsVQSXEA/tQ4HMSjfNHj3oSqNQaq5PcQk8t0s7VITx4c14rZ88ueH9ulwyhOfodjEVnPZ7P50aUCBJgDDZYdK/agmW+OhQCBT/OPO7XXaelf3KO9WC7IelV5MjH7Wt9pkBLozVFOuGN5pKc7wb99yNdgX9tCmjE2ZXRZmddu8ydgn+Kvk5F6I92f3u0e6FQKQoJCj0fbItaM5S3Mlw8MIraXveWN750va3j9cHMTjlnEhlE3YOtGe/A4U+bCqP7iSDVbyhE1uTcPBkDrB/0mu3T8tkoAeuAO0daQJkzznvRIl5IXlDOvVzE="
